### ISSUE TITLE
Doesn't work with @Configuration annotated classed

### ISSUE THREAD

**Issue by mibutec** [rinoto/spring-auto-mock#1]
When using it to wire Bean defined with @Bean in @Configuration classes it doesn't work. Think it's because the post processor starts working before any bean is instantiated. Maybe there's a better hook?

**Comment by rinoto** [comment]
Hi,
I have created a new test for your use case (see sbg.rinoto.spring.mock.AutoMockRegistryProcessorTest.shouldUseRealImplementationOfClassDefinedInConfigurationIfAvailable()), but it works for me. 

If you can write a Unit test that reproduces your problem, I will be very happy to fix it.

**Comment by mibutec** [comment]
package sbg.rinoto.spring.mock;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.mockito.Mockito.when;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import sbg.rinoto.spring.mock.ConfigurationTest.SomeConfig;

@ContextConfiguration(classes = { AutoMockRegistryPostProcessor.class,
        SomeConfig.class })
@RunWith(SpringJUnit4ClassRunner.class)
public class ConfigurationTest {
    @Autowired
    private HelloWorld helloWorld;

```
@Before
public void setup() {
    when(helloWorld.sayHello()).thenReturn("its working");
}

@Test
public void shouldAutowireTypesDefinedInComponentFromBeanAnnotation() {
    assertThat(helloWorld.sayHello(), is("its working"));
}

@Configuration
public static class SomeConfig {
    @Bean
    public HelloComponent helloComponent() {
        return new HelloComponent();
    }
}

public static interface HelloWorld {
    String sayHello();
}

public static class HelloComponent {
    @Autowired
    private HelloWorld helloWorld;
}
```

}

**Comment by rinoto** [comment]
Thanks a lot for the test case. I have added it to the repo (https://github.com/rinoto/spring-auto-mock/blob/master/src/test/java/sbg/rinoto/spring/mock/ConfigurationTest.java) and fixed it. 

Could you try again?

**Comment by mibutec** [comment]
Nice work. Lacally@Home it works nice. I'll try it on monday in our productive code.

**Comment by mibutec** [comment]
works fine
