### ISSUE TITLE
Remove direct dependencies to javax.inject

### ISSUE THREAD

**Issue by mibutec** [rinoto/spring-auto-mock#2]
In our project we use plain spring. But for using spring-auto-mock I have to add dependencies to javax.inject (or rework the code). Both is unsatisfactory.

It would be nice, if I could turn off processing of @Inject annotations to avoid NoClassDefFoundErrors (or even spring-auto-mock) would find out itself, that there are no necessary classes in classpath

**Comment by mibutec** [comment]
package sbg.rinoto.spring.mock;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.mockito.Mockito.when;

import java.net.URLClassLoader;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.BlockJUnit4ClassRunner;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import sbg.rinoto.spring.mock.ConfigurationTest.HelloComponent;
import sbg.rinoto.spring.mock.ConfigurationTest.HelloWorld;
import sbg.rinoto.spring.mock.WorksWithoutJavaxInjectTest.TestRunner;

@RunWith(TestRunner.class)
public class WorksWithoutJavaxInjectTest {
    private HelloWorld helloWorld;

```
private ClassLoader oldClassloader;

private AnnotationConfigApplicationContext context;

@Before
public void setup() throws Exception {
    oldClassloader = Thread.currentThread().getContextClassLoader();
    Thread.currentThread().setContextClassLoader(getClass().getClassLoader());
    context = new AnnotationConfigApplicationContext(AutoMockRegistryPostProcessor.class,
            HelloComponent.class);
    helloWorld = context.getBean(HelloWorld.class);
    when(helloWorld.sayHello()).thenReturn("its working");
}

@After
public void tearDown() {
    context.close();
    Thread.currentThread().setContextClassLoader(oldClassloader);
}

@Test
public void shouldAutowireTypesDefinedInComponentFromBeanAnnotation() {
    assertThat(helloWorld.sayHello(), is("its working"));
}

// reload the testclass with own classloader
public static class TestRunner extends BlockJUnit4ClassRunner {
    @SuppressWarnings("resource")
    public TestRunner(Class<?> testFileClass) throws Exception {
        super(new TestClassLoader().loadClass(testFileClass.getName()));
    }
}
```

}

/**
- Parent last classloader prohibiting access to javax.inject
  *
  */
  class TestClassLoader extends URLClassLoader {
  public TestClassLoader() {
      super(((URLClassLoader) getSystemClassLoader()).getURLs());
  }
  
  @Override
  public Class<?> loadClass(String name) throws ClassNotFoundException {
      // is class already loaded?
      Class<?> loadedClass = findLoadedClass(name);
      if (loadedClass != null) {
          return loadedClass;
      }
  
  ```
  // load bootstrap classes
  try {
      return getSystemClassLoader().getParent().loadClass(name);
  } catch (ClassNotFoundException cnfe) {
      // not a bootstrap class
  }
  
  // some parts of junit have already been loaded by systemclassloader
  if (name.startsWith("org.junit")) {
      return super.loadClass(name);
  }
  
  // the important part: prohibit access to javax.inject
  if (name.startsWith("javax.inject.")) {
      throw new ClassNotFoundException();
  }
  
  return findClass(name);
  ```
  
  }
  }

**Comment by rinoto** [comment]
Thanks (again) for the test. I have removed the hardcoded dependencies to javax.inject (Inject & Named), and I load them now only when available (as Spring does).

Should be ok now.

**Comment by mibutec** [comment]
works fine
